### ISSUE TITLE
Proposal alter models and migrations to use UUIDs for IDs

### ISSUE THREAD

**Issue by mdeloughry** [Daynnnnn/statamic-database#10]
First of all thanks for the awesome package, as you can see I'm very eager to help contribute to the package as I've already found it super useful and 100% valuable to my projects.

I'm just wondering what are your thoughts on changing the IDs for the Model and Migrations to be UUIDs to follow suit with how the Entries table is?

I don't have the time at the moment but when I've got more free time I'm happy to take a crack at it.

Thanks again for the hard work
Matt

**Comment by Daynnnnn** [comment]
So if I was building from scratch again, I probably would've opted to use UUIDs for everything for consistency. I just don't think it's worth doing now, as we're closing in on a 1st party solution, which I'd recommend switching to when it's available: https://github.com/statamic/eloquent-driver/pull/42.

That said, the official PR has been about for 14 months including the original, so who knows when that'll be :(

**Comment by ryanmitchell** [comment]
It got merged yesterday :) V1 is out:
https://github.com/statamic/eloquent-driver

**Comment by mdeloughry** [comment]
> It got merged yesterday :) V1 is out: https://github.com/statamic/eloquent-driver

Awesome that will be of use in the future thanks :D

**Comment by ryanmitchell** [comment]
I wish I'd found your repo when I was working on it! Anything you feel is missing please PR.

**Comment by Daynnnnn** [comment]
That's great! Time to archive this package 😁 I released it at the exact same time the original PR opened, so was pretty unfortunate timing haha

I'm gonna be doing a final release which allows you to transform all the data from this package to work with the official one, so I'll let you know if I run into anything while delving into how the official one works. I'm sure you guys will have covered all though!
