### ISSUE TITLE
Taxonomies don't work

### ISSUE THREAD

**Issue by asamofal** [Daynnnnn/statamic-database#3]
Hi!
### Bug with taxonomy tag
```
{{ taxonomy:categories }}
    <a href="{{ url }}">{{ title }}</a>
{{ /taxonomy:categories }}
```
Can't loop over taxonomy terms. Seems like the problem in getting `collections`.
`Statamic\Tags\Taxonomy\Terms`:
```php
protected function query()
{
    $query = Term::query()
        ->whereIn('taxonomy', $this->taxonomies->map->handle()->all());

    if ($this->collections) {
        $query->whereIn('collections', $this->collections->map->handle()->all());
    }

    $this->queryConditions($query);
    $this->queryScopes($query);
    $this->queryOrderBys($query);
    $this->queryMinimumEntries($query);

    return $query;
}
```

Because of that additional constraint based on condition for `$this->collections` we get an empty result. `$this-collections` is always true - check `parseCollections` method in the same class.

Seems we have to override `whereIn` method in our `TermQueryBuilder` where we should handle the case when it get collections column and get the collections properly (not just look at `data->collections` column in `taxonomies_terms` table).
This dumb fix is working - just don't do anything for "collections" column:
```php
public function whereIn($column, $values)
{
    if (in_array($column, ['collection', 'collections'])) {
        return $this;
    }

    $this->builder->whereIn($this->column($column), $values);

    return $this;
}
```
But this is just a stub, not a solution. Not sure if this problem related to the second one or not... but there's a chance that because of missing collections it's not possible to search by URI.

### Failed to get the list of collections by taxonomy URI
Route: `/categories/hr-hms`
`Statamic\Http\Controllers\FrontendController@index` just fails all the time there:
```php
if ($data = Data::findByUri($url, Site::current()->handle())) {
    return $data;
}
```
![image](https://user-images.githubusercontent.com/2729547/123072109-ed946e80-d41d-11eb-9c76-faa8a8ef5772.png)

I've noticed when I switch back to files `$data` is instance of `Statamic\Taxonomies\LocalizedTerm` and there's no error, but when I enable the package `$data` is instance of `Daynnnnn\StatamicDatabase\Taxonomies\Term` and there's an error. Maybe need to implement our own `findByUri` method...

Taxonomies are important part of any blog. Could you try to fix it, please?

**Comment by Daynnnnn** [comment]
Thanks for the report, I'll try sort this over the next couple days

**Comment by asamofal** [comment]
@Daynnnnn Great, thanks!
