### ISSUE TITLE
Potential Issues Accessing Entry Variables in Antlers

### ISSUE THREAD

**Issue by Jgbroz** [Daynnnnn/statamic-database#8]
Heya, 
First off thanks for the current repo it's been exactly what we've needed so far so thanks man! That said I'm still fairly new to Statamic and using this project so if I am misusing it do please let me know! Essentially at the moment while trying to render out an entries variables we're unable to access them using the traditional Antlers method eg. `{{ title }}`. 

Doing a `{{ dump }}` on the template page yields the following output here:
 
![Screenshot 2022-06-22 at 15 21 51](https://user-images.githubusercontent.com/56642857/175053111-12093246-3959-4cb5-8073-3933232fc58e.png)

In order to access any of the entry variables from the rendered page we've been having to use the following approach shown below:
```
<article class="px-4">
    <section class="text-center">
        <h1 class="text-5xl font-black">{{ page:title }}</h1>
    </section>
    <section class="max-w-2xl mx-auto py-12 lg:py-20 relative z-10">
        {{ page:introduction_text }}
        {{ page:author:name }}
        {{ page:body }}
            {{ partial:if_exists src="sets/_{type}" }}
        {{ /page:body }}
    </section>
</article>
```
Again it could be on us in terms of how we form the collection and so on but do please let me know if you have any thoughts. If you need any further info or code snippets I'd be more than happy to hand them over.

Thanks and I hope you're having a great day,
George

**Comment by Daynnnnn** [comment]
Hiya! I think I've sorted this in v1.7.0 if you wanna give it a crack?

**Comment by Jgbroz** [comment]
Heya, 
Thanks for such a fast response. I've just updated my current version to 1.7 and unfortunately it didn't seem to do the trick. I guess some additional information that could be of use is that in the prior post I was only able to access variables using`{{ page:title }}` while not using Antlers new Parser changes. However with it enabled (which is what the current system was built with in mind) even `{{ page:title }}` ceases to work and from what I can see unfortunately after updating I'm unable to access any variable entries in any other way. I've attached a new dump below if that helps but otherwise please do let me know if there is any info or approaches you may want me to give a go. 

![Screenshot 2022-06-23 at 08 24 14](https://user-images.githubusercontent.com/56642857/175240441-0be6f175-97f0-4d49-b63b-f267619e743d.png)

**Comment by Daynnnnn** [comment]
That's strange, it seems to be working for me now (on both parsers) 🤔  Could you send your Statamic version over?

**Comment by Jgbroz** [comment]
Sure thing man. In the composer lock we have `"version": "v3.3.15",` atm. If it's working on your side that makes me feel like there is an inherent issue with my setup here in regards to the collections possibly. Again we're still very new to statamic so that may be an issue on our end more than anything.

**Comment by Daynnnnn** [comment]
I can actually see your selectedQueryColumns on the Entry is an array of 12 items - on 1.7.0 that value should be null (which it is for me). If you go to `vendor/daynnnnn/statamic-database/src/Entries/EntryQueryBuilder.php`, can you see if this change is present? https://github.com/Daynnnnn/statamic-database/commit/d7b6619c31f050782ad3c427b63d4641b4ece7ef

**Comment by Jgbroz** [comment]
Huh for some reason it didn't change after upgrading? I'll quickly make a manual change and have a play around thanks for the help man appreciate it massively.
![Screenshot 2022-06-23 at 08 59 35](https://user-images.githubusercontent.com/56642857/175247571-b3e26e5e-67f6-44cc-82f3-17f654d6d638.png)

**Comment by Jgbroz** [comment]
Sorry for the slight confusion but you're an absolute saint! Thank you so much man for all your help and it's all up and running now! Hope you have a great day man

**Comment by Daynnnnn** [comment]
No worries man! You too
